- name: Ensure Bind server is installed
  apt:
    name: bind9
    update_cache: yes
    state: latest

- name: Ensure that the DNS public zone configuration is in place
  copy:
    src: "files/dns-replica"
    dest: "/etc/bind/named.conf.public-zones"
    owner: root
    group: bind
    mode: '0644'

- name: Ensure that we load the public zone config
  lineinfile:
    path: "/etc/bind/named.conf"
    line: "include \"/etc/bind/named.conf.public-zones\";"
    insertafter: "EOF"

- name: Reload the configuration
  service:
    name: bind9
    state: restarted

- name: Health check that the server is listening
  debug:
    msg: "TODO"

- name: Ensure that the metrics are being collected
  debug:
    msg: "TODO"

- name: Ensure that the logs are being collected
  debug:
    msg: "TODO"

