- name: Ensure Bind server is installed
  apt:
    name: bind9
    update_cache: yes
    state: latest

- name: Ensure that the DNS public zone configuration is in place
  copy:
    src: "files/dns-replica"
    dest: "/etc/bind/named.conf.public-zones"
    owner: root
    group: bind
    mode: '0644'

- name: Ensure that we load the public zone config
  lineinfile:
    path: "/etc/bind/named.conf"
    line: "include \"/etc/bind/named.conf.public-zones\";"
    insertafter: "EOF"

- name: Reload the configuration
  service:
    name: bind9
    state: restarted

- name: Register new DNS server with something
  debug: msg="TODO Register somewhere so that the primary can add this machine to the allow list of replicas"

- name: Check if port 53 is listening
  wait_for:
    port: 53
    delay: 5
    timeout: 10
    msg: "Timeout waiting for 80 to respond"
  register: port_check
  ignore_errors: yes

- name: Try to restart bind9 if not started
  service:
    name: bind9
    state: started
    enabled: yes
  when: port_check.failed == true

- name: Ensure that the metrics are being exposed
  blockinfile:
    path: "/etc/bind/named.conf.options"
    block: |
      statistics-channels {
        inet 127.0.0.1 port 8053;
      };
    insertafter: "EOF"
    backup: yes
    validate: "named-checkconf /etc/bind/named.conf"

- name: Ensure that metrics are being collected
  debug: 
    msg: "TODO"

- name: Ensure that the logs are being collected
  debug:
    msg: "TODO"

