- hosts: all
  tasks:
    - name: get info on an instance
      connection: local
      gcp_compute_instance_info:
        zone: us-central1-a
        project: dns-server-22102021
        auth_kind: serviceaccount
        service_account_file: "/tmp/sa-key.json"

    - name: create a disk
      gcp_compute_disk:
        name: dns-disk-instance
        size_gb: 30
        source_image: projects/ubuntu-os-cloud/global/images/family/ubuntu-2004-lts
        zone: us-central1-a
        #project: "{{ gcp_project }}"
        #auth_kind: "{{ gcp_cred_kind }}"
        #service_account_file: "{{ gcp_cred_file }}"
        project: dns-server-22102021
        auth_kind: serviceaccount
        service_account_file: "/tmp/sa-key.json"
        state: "{{ envstate | default('present') }}"
      register: disk
      ignore_errors: true

    - name: create a network
      gcp_compute_network:
        name: dns-network-instance
        auto_create_subnetworks: true
        #project: "{{ gcp_project }}"
        project: dns-server-22102021
        #auth_kind: "{{ gcp_cred_kind }}"
        auth_kind: serviceaccount
        service_account_file: "/tmp/sa-key.json"
        state: "{{ envstate | default('present') }}"
      register: network
      ignore_errors: true

    - name: create a address
      gcp_compute_address:
        name: dns-address-instance
        region: us-central1
        #project: "{{ gcp_project }}"
        project: dns-server-22102021
        auth_kind: serviceaccount
        #auth_kind: "{{ gcp_cred_kind }}"
        service_account_file: "/tmp/sa-key.json"
        state: "{{ envstate | default('present') }}"
      register: address
      ignore_errors: true

    - name: create a instance
      gcp_compute_instance:
        name: dns-server-1 
        machine_type: e2-micro
        disks:
        - auto_delete: 'true'
          boot: 'true'
          source: "{{ disk }}"
        metadata:
          #startup-script-url: gs:://graphite-playground/bootstrap.sh
          startup-script: |
              #! /bin/bash
              apt update
              apt -y install apache2
              cat <<EOF > /var/www/html/index.html
              <html><body><p>Linux startup script added directly.</p></body></html>
        labels:
          serverrole: dns
        network_interfaces:
        - network: "{{ network }}"
          access_configs:
          - name: External NAT
            nat_ip: "{{ address }}"
            type: ONE_TO_ONE_NAT
        zone: us-central1-a
        project: dns-server-22102021
        auth_kind: serviceaccount
        service_account_file: "/tmp/sa-key.json"
        state: "{{ envstate | default('present') }}"
